// src/components/CreateStatus.vue
<template>
	<form v-on:keyup.enter="submitForm">
		<h1>New Status</h1>

		<fieldset>
			<label>Content</label>
			<textarea maxlength="500" type="textarea" v-model="content"></textarea>
		</fieldset>

		<button @click="submitForm" :disabled="loading">Submit</button>
	</form>
</template>

<script>
import router from '../router'

export default {
	name: 'CreateStatus',
	data () {
		return {
			content: '',
		}
	},
	beforeMount () {
		if (!this.$store.state.username)
			router.back()
	},
	computed: {
		loading () {
			return this.$store.state.loading
		}
	},
	methods: {
		submitForm (e) {
			e.preventDefault()
			let { content, pitch } = this
			this.$store.dispatch('createStatus', { content })
		}
	}
}
</script>

// ui/src/pages/CreateStatus.svelte
<script>
  import { createStatus } from '../actions'
  import { userCheck, redirect } from '../utils'
  userCheck()

  let content = ''
  let loading = false

  async function submitForm (evt) {
    loading = true
    const status = await createStatus(content)
    redirect(`/status/${status.id}`)
  }
</script>

<section>
  <h1>New Status</h1>

  <form on:keyup.enter={submitForm}>
    <fieldset>
      <label>Content</label>
      <textarea bind:value={content} maxlength=500 type="textarea" />
    </fieldset>

    <button disabled={loading} on:click|preventDefault={submitForm}>
      Submit
    </button>
  </form>
</section>
