// src/components/Register.vue
<template>
	<form v-on:keyup.enter="submitForm">
		<h1>Register</h1>
		<fieldset>
			<label>Username</label>
			<input type="text" v-model="username"></input>
		</fieldset>

		<fieldset>
			<label>Email</label>
			<input type="email" v-model="email"></input>
		</fieldset>

		<fieldset>
			<label>Password</label>
			<input type="password" v-model="password"></input>
		</fieldset>

		<fieldset>
			<label>Password Confirmation</label>
			<input type="password" v-model="confirmPassword"></input>
		</fieldset>

		<button @click="submitForm" :disabled="loading">Submit</button>
	</form>
</template>

<script>
export default {
	name: 'Register',
	data () {
		return {
			username: '',
			password: '',
			confirmPassword: '',
			email: ''
		}
	},
	beforeMount () {
		if (this.$store.state.username)
			router.back()
	},
	computed: {
		loading () {
			return this.$store.state.loading
		}
	},
	methods: {
		submitForm (e) {
			e.preventDefault()
			let { username, email, password, confirmPassword } = this
			this.$store.dispatch('register', { username, password, confirmPassword, email })
		}
	}
}
</script>

<style>

</style>

// ui/src/pages/Register.svelte
<script>
  import { register } from '../actions'
  export let params

  let username = ''
  let password = ''
  // Breaking with naming conventions here due to convenience when it comes to submitting the
  // API request — this is the key name the API expects.
  let password_confirmation = ''
  let email = ''
  let loading = false

  async function submitForm () {
    loading = true
    await register({ username, password, password_confirmation, email }, params.code)
    loading = false
  }
</script>

<form on:keydown.enter={submitForm}>
  <h1>Register</h1>

  <fieldset>
    <label>Username</label>
    <input bind:value={username} type="text" />
  </fieldset>

  <fieldset>
    <label>Email</label>
    <input bind:value={email} type="text" />
  </fieldset>

  <fieldset>
    <label>Password</label>
    <input bind:value={password} type="password" />
  </fieldset>

  <fieldset>
    <label>Confirm Password</label>
    <input bind:value={password_confirmation} type="password" />
  </fieldset>

  <button disabled={loading} on:click|preventDefault={submitForm}>
    Submit
  </button>
</form>
