// ui/src/pages/Login.svelte
<script>
  import { login } from '../actions'

  let username = ''
  let password = ''
  let remember = false
  let loading = false

  async function submitForm () {
    loading = true
    await login({ username, password, remember_me: remember })
    loading = false
  }
</script>

<form on:keydown.enter={submitForm}>
  <h1>Login</h1>

  <fieldset>
    <label>Username</label>
    <input bind:value={username} type="text" />
  </fieldset>

  <fieldset>
    <label>Password</label>
    <input bind:value={password} type="password" />
  </fieldset>

  <fieldset>
    <label class="text--vmid">
      <input bind:checked={remember} type="checkbox" class="text--vmid" />
      Remember me
    </label>
  </fieldset>

  <button disabled={loading} on:click|preventDefault={submitForm}>
    Submit
  </button>
</form>

// src/components/Login.vue
<template>
	<form v-on:keyup.enter="submitForm">
		<h1>Login</h1>

		<fieldset>
				<label>Username</label>
				<input type="text" v-model="username" />
		</fieldset>

		<fieldset>
				<label>Password</label>
				<input type="password" v-model="password" />
		</fieldset>

		<button @click="submitForm" :disabled="loading">Submit</button>
	</form>
</template>

<script>
import router from '../router'

export default {
	name: 'Login',
	data () {
		return {
			username: '',
			password: ''
		}
	},
	beforeMount () {
		if (this.$store.state.username)
			router.back()
	},
	computed: {
		loading () {
			return this.$store.state.loading
		}
	},
	methods: {
		submitForm () {
			let { username, password } = this
			this.$store.dispatch('login', { username, password })
		}
	}
}
</script>

<style>

</style>
